main:
  - name: home
    pageRef: / 
    weight: 10
  - name: work
    pageRef: /work
    weight: 20
  - name: about
    pageRef: /about.html
    weight: 30
  - name: contact
    pageRef: /contact.html
    weight: 40
